pipeline {
    agent any
    parameters {
        choice(name: 'NUMBER',
            choices: [10,20,30,40,50,60,70,80,90],
            description: 'Select the value for F(n) for the Fibonnai sequence.')
    }
    options {
        buildDiscarder(logRotator(daysToKeepStr: '10', numToKeepStr: '10'))
        timeout(time: 12, unit: 'HOURS')
        timestamps()
    }
    triggers {
        cron '@midnight'
    }
    stages {
        stage('Make executable') {
            steps {
                dir("${env.WORKSPACE}/ch03_06"){
                     sh('pwd && ls')
                     sh('chmod +x ./algorithm.sh')
                }
            }
        }
        stage('Test') {
            steps {
                echo "BUILD_NUMBER = $BUILD_NUMBER"
                dir("${env.WORKSPACE}/ch03_06"){
                    sh('pwd')
                    sh('./algorithm.sh')
                    sh("cp ./report.txt ${BUILD_NUMBER}.txt")
                    // archiveArtifacts allowEmptyArchive: true, artifacts: "*.txt", fingerprint: true, onlyIfSuccessful: true 

                }
                

            }
        }
    }
    post{
            always{
                  echo 'archive artifacts'
                  dir("${env.WORKSPACE}/ch03_06"){
                    archiveArtifacts allowEmptyArchive: true, artifacts: "${BUILD_NUMBER}.txt.txt", fingerprint: true, onlyIfSuccessful: true 

                  }
                  
            }
    }
}
